include:
  # Totem (XIAO BLE)
  - board: seeeduino_xiao_ble
    shield: totem_left
  - board: seeeduino_xiao_ble
    shield: totem_right
  - board: seeeduino_xiao_ble
    shield: totem_dongle prospector_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  # KLOR (nice!nano v2)
  - board: nice_nano_v2
    shield: klor_left
  - board: nice_nano_v2
    shield: klor_right
  - board: nice_nano_v2
    shield: klor_dongle prospector_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  # Optional settings_reset for KLOR
  - board: nice_nano_v2
    shield: settings_reset
